name: 10-4 Good City
markdown: redcarpet
pygments: true
siteurl: "http://agautsc.github.io/10-4-good-city/"
baseurl: /10-4-good-city
prose:
 metadata:
  _posts:
   - name: "published"
     field:
       element: "select"
       label: "Published"
       placeholder: "Published"
       options:
        - name: "True"
          value: "true"
        - name: "False"
          value: "false"
   - name: "layout"
     field:
       element: "select"
       label: "Select layout"
       placeholder: "Layout"
       options:
         - name: "Post"
           value: "post"
         - name: "Default"
           value: "default"
   - name: "tags"
     field:
       element: "multiselect"
       label: "Add Tags"
       placeholder: "Choose tags"
       options: 
        - name: "Techonology"
          value: "techonology"
        - name: "Transportation"
          value: "transporation"
